# Generated by Django 4.2.11 on 2024-05-05 16:53

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('from_hidden', models.TextField()),
                ('to_hidden', models.TextField()),
                ('cost', models.TextField()),
                ('rate', models.TextField()),
                ('date_booking', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
