# Generated by Django 4.2.11 on 2024-05-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_search_remove_booking_cost_booking_billing_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='date_search',
            new_name='search_date',
        ),
        migrations.AddField(
            model_name='search',
            name='distance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='travel_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='terms',
            field=models.BooleanField(default=False),
        ),
    ]
