# Generated by Django 4.2.11 on 2024-05-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_date_search_search_search_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
